---
client:
    benign_training:
        batch_size: 64
        learning_rate: 0.02
        num_epochs: 2
        optimizer: SGD
    clip: ~
    malicious:
        attack_start: 1
        attack_stop: 1
        backdoor:
            augment_data: true
            augment_times: 200
            remove_from_benign_dataset: true
            target_label: 2
            train: [389,561,874,41861,3378,3678,4528,9744,19165,19500,21422,22984,32941,34287,34385,36005,37365,37533,38658,38735,39824,40138,47026,48003,48030,49163,49588]
            test: [41336,1605,47001]
            type: semantic_pixel_pattern
            trigger_position: 4
#            augment_data: false
#            augment_times: 0
#            remove_from_benign_dataset: true
#            target_label: 2
#            type: edge
#            edge_case_type: NorthWesternEdgeCase
        evasion:
            args:
                norm_type: l2
                pgd_factor: ~
                scale_factor: 100
            name: NormBoundPGDEvasion
        objective:
            args:
                learning_rate: 0.1
                num_batch: 10
                num_epochs: 6
                optimizer: SGD
                poison_samples: 20
                step_decay: true
                noise_level: ~
                attacker_full_dataset: false
            name: TargetedAttack
        multi_attacker_scale_divide: true
    model_name: resnet18
dataset:
    augment_data: true`
    data_distribution: dirichlet
    dataset: cifar10
environment:
    attack_frequency: 1.0
    attacker_full_knowledge: true
    experiment_name: cifar_bounds
#    load_model: ../models/resnet18.h5
    num_clients: 100
    num_malicious_clients: 1
    num_selected_clients: 40
    use_config_dir: true
    save_weight_outside_bound: 0.01
job:
    cpu_cores: 20
    cpu_mem_per_core: 4096
    gpu_memory_min: 10240
    minutes: 10
    use_gpu: 1
server:
    aggregator:
        name: FedAvg
    global_learning_rate: 1
    num_rounds: 50
    num_test_batches: 50
...