---
client:
    benign_training:
        batch_size: 64
        learning_rate: 0.02
        num_epochs: 2
        optimizer: SGD
    clip:
        type: median_l2
        value: 5.
    malicious:
        attack_start: 1
        attack_stop: 1005
        backdoor:
            augment_data: true
            augment_times: 50
            remove_from_benign_dataset: false
            target_label: 2
            test:
            - 41336
            - 1605
            - 47001
            train:
            - 389
            - 561
            - 874
            - 41861
            - 3378
            - 3678
            - 4528
            - 9744
            - 19165
            - 19500
            - 21422
            - 22984
            - 32941
            - 34287
            - 34385
            - 36005
            - 37365
            - 37533
            - 38658
            - 38735
            - 39824
            - 40138
            - 47026
            - 48003
            - 48030
            - 49163
            - 49588
            type: semantic
        evasion:
            args:
                norm_type: median_l2
                pgd_factor: null
                scale_factor: 20
            name: NormBoundPGDEvasion
        multi_attacker_scale_divide: true
        objective:
            args:
                anticipate_steps: 9
                learning_rate: 0.1
                model_type: resnet18
                num_batch: 10
                num_epochs: 6
                optimizer: SGD
                poison_samples: 20
                step_decay: true
                optimization_method: A
            name: AnticipateAttack
    model_name: resnet18
dataset:
    augment_data: true
    data_distribution: dirichlet
    dataset: cifar10
environment:
    attack_frequency: 1.0
    attacker_full_knowledge: true
    experiment_name: cifar_edgecase
    load_model: ../models/resnet18.h5
    num_clients: 100
    num_malicious_clients: 5
    num_selected_clients: 40
    use_config_dir: true
    limit_tf_gpu_mem_mb: 8096

hyperparameters:
    args:
        client:
            malicious:
                backdoor:
                    test:
                    - 41336
                    - 1605
                    - 47001
                    train:
                    - 389
                    - 561
                    - 874
                    - 41861
                    - 3378
                    - 3678
                    - 4528
                    - 9744
                    - 19165
                    - 19500
                    - 21422
                    - 22984
                    - 32941
                    - 34287
                    - 34385
                    - 36005
                    - 37365
                    - 37533
                    - 38658
                    - 38735
                    - 39824
                    - 40138
                    - 47026
                    - 48003
                    - 48030
                    - 49163
                    - 49588
                    type: semantic
                evasion:
                    args:
                        norm_type: median_l2
                        pgd_factor: null
                        scale_factor: 20
                    name: NormBoundPGDEvasion
                objective:
                    args:
                        anticipate_steps: 9
                        learning_rate: 0.1
                        model_type: resnet18
                        num_batch: 10
                        num_epochs: 6
                        step_decay: true
                    name: AnticipateAttack
job:
    cpu_cores: 20
    cpu_mem_per_core: 4096
    gpu_memory_min: 10240
    minutes: 1440
    use_gpu: 1
server:
    aggregator:
        name: FedAvg
    global_learning_rate: 1.0
    num_rounds: 1000
    num_test_batches: 50
...
