---
client:
    benign_training:
        batch_size: 32
        learning_rate: 0.001
        num_epochs: 5
        optimizer: Adam
    clip:
        type: median_l2
        value: 10.0
    malicious:
        multi_attacker_scale_divide: true
        attack_start: 1
        attack_stop: 5
#        backdoor:
#            augment_times: 0
#            aux_samples: -1
#            source_label: 7
#            target_label: 1
#            tasks: 30
#            type: edge
#            edge_case_type: EuropeanSevenEdgeCase
#            edge_case_p: 0.95
        backdoor:
            type: tasks
            tasks: 30
            source_label: 7
            target_label: 1
            aux_samples: -1
            augment_times: 0
        evasion:
            args:
                norm_type: l2
                scale_factor: 30
#                clipping_bound: 0.01
            name: NormBoundPGDEvasion
        objective:
            args:
                learning_rate: 0.1
                num_batch: 25
                num_epochs: 5
                optimizer: SGD
                poison_samples: 10
                reduce_lr: false
                step_decay: true
#                optimization_method: A
                anticipate_steps: 5
                regular_train: true
            name: AnticipateTfAttack
    model_name: lenet5_mnist
dataset:
    data_distribution: nonIID
    dataset: femnist
environment:
    attack_frequency: 1.0
    attacker_full_knowledge: true
    attacker_full_dataset: true
    experiment_name: backdoor_tasks_bound_lenet
    load_model: ../models/lenet5_emnist_088.h5
    num_clients: 3383
    num_malicious_clients: 30 # 113
    num_selected_clients: 30
    num_selected_malicious_clients: 10
    use_config_dir: true
job:
    cpu_cores: 20
    cpu_mem_per_core: 4096
    gpu_memory_min: 10240
    minutes: 240
    use_gpu: 1
server:
    aggregator:
        name: FedAvg
    global_learning_rate: -1
    num_rounds: 10
    num_test_batches: 50
...
